---

- name: Debian | OS variables
  include_vars:
    file: Ubuntu.yml

- name: Debian | Install python-apt
  apt:
    pkg: python-apt

- import_tasks: webupd8_for_debian.yml
  when: "ansible_distribution != 'Ubuntu'"

- import_tasks: webupd8_for_ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Debian | Update repository
  apt: 
    update_cache: true

- name: Debian | Accept Oracle License
  debconf:
    name: "{{ item }}"
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'
  with_items:
    - oracle-java6-installer
    - oracle-java7-installer
    - oracle-java8-installer
  when: java_needs_oracle

- name: Debian | Install Java packages
  apt:
    pkg: "{{ java_packages }}"
    state: latest

- name: Debian | Remove unwanted Java packages
  apt:
    pkg: "{{ java_packages_to_remove|default([]) }}"
    state: absent
  when: java_cleanup
